### PR TITLE
[MRG] Backend/feat/regions

### PR DESCRIPTION
**Pull request by ShmuelTreiger**
Some notes:

1) Under this schema there's no distinction, for example, between Scotland an England, they're both just UK. Not necessarily wrong, just something to consider. (Similarly, it doesn't have the various US states which I suppose are kind of analogous, so maybe it's for the best.)

2) Do we want to allow "other" countries somehow?

3) I didn't think it was worth massively re-doing countries as their own data type, or reworking how we treat them (i.e. as a "|" delineated string).

4) I'm sure this bit of code

```
                    else:
                        if user.countries_lived != "":
                            user.countries_lived += "|"
                        user.countries_lived += country
```

Can be done more prettily, but I'm bad at that kind of stuff. Input welcome.

5) Do we want to rename "country" as "region"?

### CODE REVIEW

**Review by aapeliv — CHANGES_REQUESTED** [review]
Thanks for taking this up! Some comments:

1. Let's use the alpha-3 three letter ISO code for regions, when I looked into it, it was more unique (the 2 letter codes sometimes get reshuffled). No need to include attribution for that.
1. Could you switch to storing the countries visited/lived in separate tables? Similar to language ability (but without the actual ability level): that would allow filtering based on country through a fast join and is just a lot cleaner than a manual array encoding in-db.
1. Please call them regions :)
1. Could you please copy the `regions.json` from the other pr verbatim? The file you've created has some encoding issues with non-ASCII chars (and is missing alpha3, see above).

**Comment by aapeliv** [comment]
>     1. Under this schema there's no distinction, for example, between Scotland an England, they're both just UK. Not necessarily wrong, just something to consider. (Similarly, it doesn't have the various US states which I suppose are kind of analogous, so maybe it's for the best.)

Yeah, that's ok. States and sub-regions are not a very well standardised thing, and then we'd have to start adding sub-regions for whenever people wanted to have their country's states or whatever, etc. I mean we could have some overlapping regions if needed.



>     2\. Do we want to allow "other" countries somehow?

No, not needed at the moment.

>     3\. I didn't think it was worth massively re-doing countries as their own data type, or reworking how we treat them (i.e. as a "|" delineated string).

See comment above. This is important for fast filtering and e.g. grouping people by countries lived, etc, etc.

> Do we want to rename "country" as "region"?

Yes please.

**Comment by ShmuelTreiger** [comment]
> 1. Let's use the alpha-3 three letter ISO code for regions, when I looked into it, it was more unique (the 2 letter codes sometimes get reshuffled). No need to include attribution for that.

Sure. I was going based off #470 for guidance.
Included attribution is more for ease of updating more than anything, but happy to remove

> 4. Could you please copy the `regions.json` from the other pr verbatim? 

Not sure what you mean by this. Which pr? You mean from the website I grabbed it from? I did copy it verbatim?

>The file you've created has some encoding issues with non-ASCII chars (and is missing alpha3, see above).

I noticed the ASCII issue, but figured it would get dealt with in the front end

**Comment by aapeliv** [comment]
> > 1. Could you please copy the `regions.json` from the other pr verbatim?
> 
> Not sure what you mean by this. Which pr?

This one: https://github.com/Couchers-org/couchers/pull/476

**Pull request closed without merging**
