### PR TITLE
Use relative imports in protocol definitions

### PR DESCRIPTION
**Pull request by kalvdans**
Fixup the broken generated code in a postprocessing step.

**Backend checklist**
- [x] Formatted my code by running `isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [x] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by kalvdans** [comment]
Since I'm rolling my own generate_protos.sh I need help to adapt the one in the repository. (don't ask why, long story)

**Comment by aapeliv** [comment]
Thanks! This is a great start; I'd love to get the proto imports fixed. Some comments:

* If you generate it straight into `.../proto`, then you have to have those folders in the repo already. Won't be an issue for you since they were generated before, but will fail on first run. You'll need to add a `mkdir -p` or then just add an empty folder with a `.gitignore` (I'd prefer this, then the structure is clear before running the script)
* I think you need to also change `.../src` to `.../src/proto` for the other ones, not just python

**Comment by aapeliv** [comment]
@kalvdans: are you happy for me to push into this repo to fix this up for the non-python part? Would you prefer `mkdir -p` or empty dirs with a `.gitkeep`/`.gitignore`; I'd prefer the latter (to have the right directory structure in git, maybe even a readme that says "the contents of this folder are generated by the protocol buffer compiler...").

**Comment by kalvdans** [comment]
> @kalvdans: are you happy for me to push into this repo to fix this up for the non-python part?

Yes please!

> Would you prefer `mkdir -p` or empty dirs with a `.gitkeep`/`.gitignore`; I'd prefer the latter (to have the right directory structure in git, maybe even a readme that says "the contents of this folder are generated by the protocol buffer compiler...").

An `mkdir` will give a easier gitignore expression so I think I prefer that. But I'm not going to complain if you let git create the directory.

**Comment by aapeliv** [comment]
@kalvdans: fixed now; have a look

**Review by aapeliv — APPROVED** [review]
Feel free to merge if you're happy with it

**Pull request merged**
