### PR TITLE
Update mobile auth bg to be same as on desktop for soft beta

### PR DESCRIPTION
**Pull request by aapeliv**
These might need to be updated later with even better pictures, but this lets us release the soft beta.

Does a bit of #774 :P

### CODE REVIEW

**Comment by aapeliv** [comment]
It's got `background-size: contain` now, which makes it too small, should be `cover`, but the design is made for a light picture, so it's hard to see the text on the dark background...

**Comment by lucaslcode** [comment]
I am going to push to this branch

**Review by lucaslcode — APPROVED** [review]
@aapeliv double check and merge

**Comment by aapeliv** [comment]
Works, merging

**Pull request merged**
