### PR TITLE
Static rendering of auth pages

### LINKED ISSUE #1760: Server Side Rendering
Some things that we'd want to do, and why we care, in order of importance:

1. Pre-rendering a list of static pages (e.g. /about, /blog/..., etc; list known at build time), so we could do the landing site in react and burn the vue shitshow
2. Nice link previews for profiles (or TBA invitation links)
3. Incrementally adding rendering to a set of other classes of pages, e.g. events, profiles, etc. This would hugely help SEO with crawlers being able to read some real site content.
4. Rendering everything server side to make the experience faster for users

1 is pretty high priority, but seems it might be possible with CRA much easier: https://create-react-app.dev/docs/pre-rendering-into-static-html-files. We will want 2 at some point too, but it might be able possible to do some server-side tweakery that just replaces/adds meta tags/etc. It would be great to do 3 sometime too, especially once we start having more organic content. I'm not sure if we'll ever care about doing 4: it's probably expensive and quite complicated.

### PR DESCRIPTION
**Pull request by lucaslcode**
Introduces `react-snap` to close #1760 (for now).

It requires refactoring all the `<Hidden>` components out of the pages we want to statically render, others the snapshot doesn't include all breakpoints.

### CODE REVIEW

**Comment by aapeliv** [comment]
Is it not enough to use the css implementation for the <Hidden>s?

**Comment by lucaslcode** [comment]
Yes you can use CSS but the Hiddens actually change the dom based on the
viewport size, so the snapshot is taken of the wrong size

**Comment by aapeliv** [comment]
That's with the JS implementation, right? When I did this, it seemed material-ui has also a CSS implementation that uses media queries and so doesn't change the dom?

https://material-ui.com/components/hidden/#implementations

**Comment by lucaslcode** [comment]
I've introduced changes to the dockerfile to install chromium for `react-snap`. However I suspect it will take 100 years to build now. @aapeliv Can we do some kind of docker caching? We should probably be caching `node_modules` too.

**Comment by aapeliv** [comment]
> Can we do some kind of docker caching?

Yes, it'll cache stuff; but it only caches off the latest `develop` build because it's dumb.



> We should probably be caching `node_modules` too.

It's already doing that. For PRs that don't change yarn.lock it's cached.

**Comment by lucaslcode** [comment]
I am going to remove all the `Hidden`s for the auth pages anyway - though it now works with the css implementation, it has no accessibility at all since everything is now present in the DOM.

**Comment by lucaslcode** [comment]
Gonna redo this in parts

**Pull request closed without merging**
