### PR TITLE
Fix pages tests

### PR DESCRIPTION
**Pull request by aapeliv**
Sorry, should've been more careful and waited for tests before merging.

### CODE REVIEW

**Review by kalvdans — APPROVED** [review]
LGTM!

**Comment by aapeliv** [comment]
I keep on messing it up... I'm too lazy to set it up on my machine to test 😬

**Comment by aapeliv** [comment]
Seems to be fixed now

**Review by kalvdans — APPROVED** [review]
LGTM, but don't be lazy next time ;)

**Comment by aapeliv** [comment]
Ahah, I'm working in parallel on the communities/groups stuff and my database is a bit messed up at the moment, so downgrading the migrations, etc is annoying at the moment.

**Pull request merged**
