### PR TITLE
fix: #1713 - jail page keeps reloading

### LINKED ISSUE #1713: Jail page keeps reloading
Reported and recorded by Lukas: https://1drv.ms/v/s!Ajo4-4qFAquUgagRP3RS4uwakiBh5Q?e=BidB2W

### PR DESCRIPTION
**Pull request by niecnasowa**
closes #1713

**Frontend checklist**
- [x] Formatted my code with `yarn format && yarn lint --fix`
- [x] There are no warnings from `yarn lint`
- [x] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [x] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [x] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by lucaslcode** [comment]
@aapeliv can you test this? Need a user to be put in jail

**Comment by aapeliv** [comment]
> Need a user to be put in jail

I put everyone on next in jail.

**Comment by aapeliv** [comment]
This does seem to fix the problem, but I think we should fix it in some other way than to just hide the whole rest of UI? It just looks very bare?

**Comment by lucaslcode** [comment]
Yeah I guess you're right. 
@niecnasowa I thought if a better way - do you want to undo thus change, and instead, to the query in `features/useNotifications.ts`, you can disable it using the ["enabled" option](https://react-query.tanstack.com/guides/disabling-queries) if the user is jailed ~~(`useAuthStore().state.jailed`)~~ `useAuthContext().state.jailed`

**Comment by darrenvong** [comment]
> (`useAuthStore().state.jailed`)

I think it's better to do it via `useAuthContext` instead, otherwise we'll end up with two auth stores

**Comment by lucaslcode** [comment]
Sorry yes that's what I meant!

**Comment by niecnasowa** [comment]
@lucaslcode Ok, I will change it based on your comments.

**Comment by niecnasowa** [comment]
@aapeliv @darrenvong @lucaslcode Can you recheck it now?

**Review by lucaslcode — APPROVED** [review]
Great, thanks for your contribution!

**Comment by lucaslcode** [comment]
You can merge this

**Pull request merged**
