### PR TITLE
change relative paths to absolute paths

### PR DESCRIPTION
**Pull request by andreaowu**

### CODE REVIEW

**Comment by lucaslcode** [comment]
I agree we should use absolute paths, but this makes it difficult to distinguish between modules and our code. Is there anything we can do about that? Does something like `import MessagesPage from "/features/messages/MessagesPage"` (with a / at the start) work?

**Comment by andreaowu** [comment]
Hmm I don't think so?

**Comment by lucaslcode** [comment]
How about this: https://stackoverflow.com/questions/42749973/es6-import-using-at-sign-in-path-in-a-vue-js-project-using-webpack

And/or using the [custom groups](https://stackoverflow.com/questions/42749973/es6-import-using-at-sign-in-path-in-a-vue-js-project-using-webpack) function of `simple-import-sort`

That way we can have internal files starting with @ like `import x from "@/features/x"` And we could have them in a separate group.

Anyway I'm happy to give that a try in a separate pr

**Comment by darrenvong** [comment]
I think this would be quite tricky without either hacking/overriding the webpack config from Create React App (CRA), or eject from CRA so we have full control of the webpack config, as I believe it only supports having `src` as the `basePath` set by default.

**Comment by lucaslcode** [comment]
We could do the group then, at least.
Anyway, build is broken here because the mocks aren't working on the tests, I couldn't figure out why...

**Comment by darrenvong** [comment]
Uhhhh I couldn't find a good solution without ones that mention needing to modify jest's `moduleDirectories` config ([like this one](https://stackoverflow.com/questions/50171412/jest-typescript-absolute-paths-baseurl-gives-error-cannot-find-module)), which CRA doesn't support configuring so we _might_ need to hack/override some config inside it if we want to keep this. Unless you can get the `moduleNameMapper` working, because apparently that config can be [changed/supported by CRA](https://create-react-app.dev/docs/running-tests/#configuration). I didn't have much success when I tried though...

**Comment by lucaslcode** [comment]
Try this adding to `yarn test` command: https://blog.shovonhasan.com/using-absolute-imports-with-jest-in-create-react-app/

**Comment by andreaowu** [comment]
I added `--modulePaths=src` to it, I'm not sure why the tests are failing either :(

**Comment by andreaowu** [comment]
I'm going to break this up into smaller PR's, don't know where the test is failing.

**Comment by andreaowu** [comment]
*facepalm it's because a bunch of these try to `import {service} from 'service'` instead of `service/index`

**Review by lucaslcode — APPROVED** [review]
Super weird that fixed it, may be a bug in the jest mocks resolution

**Pull request merged**
