### PR TITLE
(frontend) - fix: read more bug on mobile

### LINKED ISSUE #4261: "Read more" text placement issue on landing page (unrelated to cookies banner issue)
The "Read more" text on the bottom of landing page is only partially visible on most mobile browsers (after closing cookies banner, which also covers the text, see #4128).  The text is cut off by the bottom of the browser window:

Screenshot_20240428_232246_Firefox

This is a confirmed issue on firefox, chrome, and safari - both on android and iphone. 

The text should be moved up and the font size should be increased to make it more prominent.

### PR DESCRIPTION
**Pull request by marco-digennaro**
closes #4261

- tuning some margin 
- switched position with vercel button

**Backend checklist**
- [ ] Formatted my code by running `ruff check --select I --fix . && ruff check . && ruff format .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [x] Formatted my code with `yarn format`
- [x] There are no warnings from `yarn lint --fix`
- [x] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [x] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by bakeiro** [comment]
for contextualize, this is how it looks on my phone
image

**Review by bakeiro — APPROVED** [review]
LGTM

**Comment by bakeiro** [comment]
for me looks good, not sure if @aapeliv, @nabramow has an opinion here...

**Review by nabramow — APPROVED** [review]
I also just tested and looks good to me!

**Comment by marco-digennaro** [comment]
can i merge it? what's the policy, 2 approves are enough?

**Comment by nabramow** [comment]
> can i merge it? what's the policy, 2 approves are enough?

Yeah go for it! 1 is usually enough unless that person says they want a second opinion!

**Pull request merged**
