### PR TITLE
Disable enter-to-send on host requests/replies

### LINKED ISSUE #2096: Enter key sends message unexpectedly
Subject: Message response to request to host
Description:
Hit return while writing a reply.

Results:
In replying to a message, I discovered that a carriage return *sends* the message to the recipient rather than simply moving down one line (paragraph formatting). Thus far, I have sent two single lines unexpectedly instead of a normally formatted paragraph. 

Backend version: develop-e33b9ff0
Frontend version: develop-e33b9ff0
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Page: https://app.couchers.org/messages/request/2187
User: charlesfrenchquarter (2736)

### PR DESCRIPTION
**Pull request by wbruntra**
Intending to close https://github.com/Couchers-org/couchers/issues/2096

Partially reverting https://github.com/Couchers-org/couchers/pull/2048, now using Enter key only for the "Chat" feature, not for host messages/replies, which are intended to be longer and have paragraphs. 

May want to remove enter-to-send in Chat as well, for consistency or just because, though personally I think enter-to-send makes sense for chats.

**Web frontend checklist**
- [x] Formatted my code with `yarn format && yarn lint --fix`
- [x] There are no warnings from `yarn lint`
- [x] There are no console warnings when running the app
- [ ] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by wbruntra** [comment]
Upon further consideration (thanks @aapeliv), this has been changed to use ctrl+enter to send messages, to make the change as unobtrusive as possible to casual users.

**Review by lucaslcode — DISMISSED** [review]
Thanks!!

**Comment by wbruntra** [comment]
Wait sorry, I forgot to update and re-run the tests when I changed the chat behavior.

**Review by aapeliv — APPROVED** [review]

**Comment by darrenvong** [comment]
Hmm both Facebook and Slack uses Enter to send in a chat, so I'm not sure Ctrl+Enter is the norm and seems more obscure to me 🤔

**Comment by aapeliv** [comment]
I think it should be the same everywhere for consistency

**Comment by wbruntra** [comment]
> Hmm both Facebook and Slack uses Enter to send in a chat, so I'm not sure Ctrl+Enter is the norm and seems more obscure to me thinking

As I understand it the plan is ultimately to have more visual/design differentiation between Chat and Messages, at which point I'd agree that just `Enter` should be enough within a feature called "chat." But it seems like that kind of fine-tuning should be low-priority for now.

**Pull request merged**
