### PR TITLE
[MRG] Properly escape slugify in the migration take 2

### PR DESCRIPTION
**Pull request by kalvdans**
So that it treats dash as a punctation character. Re-applies #1130

### CODE REVIEW

**Review by aapeliv — DISMISSED** [review]
LGTM!

**Comment by aapeliv** [comment]
The rule should probably be "unaccent, lowercase, then replace every char in [^0-9a-z] with `-`, remove repeated and starting/ending `-`s". Currently I get this:

```
postgres=# select slugify('this is_a  ------  test');
        slugify
-----------------------
 this-is_a--------test
(1 row)
```

It should just be `this-is-a-test`, what do you think @kalvdans ?

**Comment by kalvdans** [comment]
> The rule should probably be "unaccent, lowercase, then replace every char in [^0-9a-z] with `-`, remove repeated and starting/ending `-`s". Currently I get this:
> 
> ```
> postgres=# select slugify('this is_a  ------  test');
>         slugify
> -----------------------
>  this-is_a--------test
> (1 row)
> ```
> 
> It should just be `this-is-a-test`, what do you think @kalvdans ?

I agree, let me look into why `"  ------  "` doesn't match a single `[^0-9a-z]+`, might be something with greediness of the patterns.

**Comment by aapeliv** [comment]
> I agree, let me look into why `" ------ "` doesn't match a single `[^0-9a-z]+`, might be something with greediness of the patterns.

Sorry. What you have now works. What's in the DB currently does not work. I read/misunderstood the regexp wrong.

But I think we should remove the underscore

**Review by aapeliv — APPROVED** [review]
LGTM

**Pull request merged**
