### PR TITLE
Fix firefox map search padding

### LINKED ISSUE #1365: Map search bar and search results lower bar spacing is off on mobile and looks bad
Subject: Map search bar and search results lower bar spacing is off on mobile and looks bad
Description:
1. Visit search page
2. Type in Madison and perform search
3. Search results appear at bottom of screen and profile "snippets" are cut off. Search bar at top of map is also cut off. See screenshot below

Results:
The positioning of the search results at the bottom of the screen should not be "cut off" and be offscreen. The search bar should also have space between the search bar and top navbar.

Backend version: develop-ae67a07c
Frontend version: develop-ae67a07c
User Agent: Mozilla/5.0 (Android 11; Mobile; rv:89.0) Gecko/89.0 Firefox/89.0
Page: https://app.couchers.org/search?query=Madison%2C+wi#loc=0.89/48.8/-36.7
User (spoofable): jesse (57)

### PR DESCRIPTION
**Pull request by lucaslcode**
might close #1365

### CODE REVIEW

**Comment by lucaslcode** [comment]
@AllhandsNoFeet does [this preview](https://frontend-bugfix-firefox-search-margin--frontend.preview.couchershq.org/) fix the search bar padding for you?

**Comment by jesseallhands** [comment]
I tried it on desktop (small window) and the padding looks fine there:

image


But on the firefox browser of my Note 20 Ultra there still are issues with padding:
image

image

**Comment by lucaslcode** [comment]
@AllhandsNoFeet I downloaded firefox on my android and I can't reproduce it.
However, I noticed in your screenshot you went to next.couchershq.org. Can you try the specific preview link for this branch?
Here it is: https://frontend-bugfix-firefox-search-margin--frontend.preview.couchershq.org/

**Comment by lucaslcode** [comment]
This was semi fixed in this PR but it didn't look good and I had to get jesse to check it (couldn't reproduce on my firefox android) so I think I'll just close this

**Pull request closed without merging**
