### PR TITLE
fix: lowercases usernames/emails before sending to backend

### LINKED ISSUE #1657: Signup form lowercasing
Right now it doesn't accept mixed-case when it requires lowercase. E.g. typing in `Aapeli28` (as one does automatically on iPhone), it's not accepted.

This should lowercase as one is typing.

### LINKED ISSUE #1728: Signup page considers emails with periods in the username as invalid.
The signup page will not let you create accounts using emails with periods in the name.
Here is an example of me trying to enter in an email (granted, it's not my real email address) with a period in it. If you remove the period, the registration process can successfully go to the next stage.
invalid email
This is a problem, because some folks have emails with periods in them, and they wouldn't be able to sign up with them in this current state.

### PR DESCRIPTION
**Pull request by darrenvong**
Closes #1657. Closes #1728. Lowercasing as the user type requires more code changes (making the input specifically into a controlled component) and not sure it's worth it if lowercasing at submission also works.

Updated error message and validation regexp so it doesn't say the username can only have lowercase letter anymore.
Screenshot 2021-07-25 at 17 59 34

**Frontend checklist**
- [x] Formatted my code with `yarn format && yarn lint --fix`
- [x] There are no warnings from `yarn lint`
- [x] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [x] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [x] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by aapeliv** [comment]
Emails should also be lowercased!

**Comment by darrenvong** [comment]
Does the backend currently error when user types in email with capitals? I'll fix it here too 👍

**Comment by aapeliv** [comment]
> Does the backend currently error when user types in email with capitals? I'll fix it here too 👍

Yep

**Review by lucaslcode — CHANGES_REQUESTED** [review]
Looks good, how about signup email?

**Comment by darrenvong** [comment]
> Looks good, how about signup email?

It's already done here. Unless there's another spot I overlooked?
https://github.com/Couchers-org/couchers/blob/7f0db6b1583a0a7db2d081f2e2af8297fa036c61/app/frontend/src/features/auth/signup/BasicForm.tsx#L44

**Comment by lucaslcode** [comment]
Did you see #1728 ? I tried using upper case on preview and it didn't work.

**Review by lucaslcode — DISMISSED** [review]
Ah I see you added the i flag

**Review by lucaslcode — CHANGES_REQUESTED** [review]
The email regex validation needs the i flag too

**Review by lucaslcode — APPROVED** [review]

**Pull request merged**
