### PR TITLE
[WIP/Help] Backend/feature/user hiding/make community group tests explicit

### PR DESCRIPTION
**Pull request by aapeliv**
Reopened #1094.

GitHub closed that one since I renamed the branch. I had to rename the branch, there were problems because it started with a string that was the same name as another branch.

### CODE REVIEW

**Comment by ShmuelTreiger** [comment]
To add more details:

I'm attempting to explicitly test hidden users in groups and communities. In the base branch (user hiding), I just added an invisible user to each group and community and assumed that if all tests are passing, everything must be OK. Less than ideal approach. However, the proximity stuff in communities has me beat. Adding users changes the results of all the tests. And then I couldn't figure out how to test GetNearbyUsers. So I figured the base branch will do for now and someone who understands this better can fix it up at some point if they feel like it.

**Comment by aapeliv** [comment]
@ShmuelTreiger: sorry, I don't understand what's going on here.

If you add a hidden/deleted user, then that should be sufficient: they shouldn't show up in any of the queries, right?

**Comment by aapeliv** [comment]
Should we close this one too and work instead on top of the new PR?

**Comment by ShmuelTreiger** [comment]
Yes, I was going to just rebase it

**Comment by aapeliv** [comment]
@ShmuelTreiger: I'll close this PR, feel free to re-open. It's better that way so it doesn't get confusing about who the author is, etc.

**Pull request closed without merging**
