### PR TITLE
Comma-separated countries lists in About

### LINKED ISSUE #1997: Apply multicolumn to visited and lived-in countries
Subject: Apply multicolumn to visited and lived-in countries
Description:
Added new countries to the list I've visited

Results:
Been visiting more than 80 countries, so when displayed the list is quite long; using a single column is probably not the best way.
If using flex, multiple columns could be allowed; or, list could be horizontally displayed, separating countries even with something simple (comma, column, hyphen, etc.)

Backend version: develop-b8a97954
Frontend version: develop-b8a97954
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
Page: https://app.couchers.org/profile/about
User: daniele (4567)

### PR DESCRIPTION
**Pull request by guisers**
Closes #1997 by changing the vertical unordered lists of regions visited/lived to comma-separated lists.

A bite-sized first PR 🎉 
I did pore through the contributing guide but lmk if there's anything I can do to improve my contributing workflow!

**Web frontend checklist**
- [x] Formatted my code with `yarn format && yarn lint --fix`
- [x] There are no warnings from `yarn lint`
- [x] There are no console warnings when running the app
- [x] Added any new components to storybook
- [x] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [x] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Review by lucaslcode — APPROVED** [review]
Love a fix with a negative line count!
This is really thorough, thanks so much.

Just note we are transitioning to using react-i18n for all strings, but this bit isn't moved yet so no worries.

**Comment by lucaslcode** [comment]
Also side note which you probably realized already, ignore the vercel stuff for the moment.

**Comment by guisers** [comment]
Thanks @lucaslcode! Do I go ahead and merge or will someone on the core team do it? 

I did notice that the strings aren't consistent throughout the platform yet 😂 I could help with some of that refactoring for my next PR...

**Comment by guisers** [comment]
Ignore the close/reopen... butter fingers on my cell phone 😂

**Comment by lucaslcode** [comment]
You merge, it's satisfying and the author is better placed to resolve merge conflicts if there are any :)

**Pull request merged**
