### PR TITLE
Upgrade Datepicker to prep for material-ui upgrade

### PR DESCRIPTION
**Pull request by nabramow**
This PR is prep for upgrading Material-UI to v5 (from v4). We need to upgrade our material datepicker package to the newer one and make the breaking changes to the Datepicker.

Breaking this upgrade into smaller PRs so we can better review and make sure we're not introducing any bugs.

**TO TEST:**
- We are using Datepicker several places, make sure they still work ok: Event page selecting event date, sign up for new account, new host request form

**Web frontend checklist**
- [  ] Formatted my code with `yarn format`
- [ ] There are no warnings from `yarn lint --fix`
- [ ] There are no console warnings when running the app
- [ N/A ] Added any new components to storybook
- [ N/A ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by darrenvong** [comment]
I made a tiny bit of progress on fixing _some_ tests, but dang, I'm not sure it's possible to even test some of the scenario anymore with the new picker, as it weirdly seems to render it differently from what you see in a real browser environment (e.g. typing directly in the input seems impossible 😕 )

**Comment by nabramow** [comment]
> I made a tiny bit of progress on fixing _some_ tests, but dang, I'm not sure it's possible to even test some of the scenario anymore with the new picker, as it weirdly seems to render it differently from what you see in a real browser environment (e.g. typing directly in the input seems impossible 😕 )

@darrenvong Looks like you're not alone at least. Maybe this will help? Same issue they are posting when upgrading to v5. Seems to kinda make sense with the behavior we both experienced.

https://github.com/mui/material-ui/issues/27038

It seems like kiiiiiind of a hack, but alas.

**Comment by darrenvong** [comment]
> > I made a tiny bit of progress on fixing _some_ tests, but dang, I'm not sure it's possible to even test some of the scenario anymore with the new picker, as it weirdly seems to render it differently from what you see in a real browser environment (e.g. typing directly in the input seems impossible 😕 )
> 
> @darrenvong Looks like you're not alone at least. Maybe this will help? Same issue they are posting when upgrading to v5. Seems to kinda make sense with the behavior we both experienced.
> 
> [mui/material-ui#27038](https://github.com/mui/material-ui/issues/27038)
> 
> It seems like kiiiiiind of a hack, but alas.

Ooh that's a good find, wish I've searched a bit more on the web first rather than trying so hard to work with/around the quirks!
And I guess it could be worse, at least it's a mean to point the import system to the right datepicker! I'll try to have a look when I find a bit of time again

**Comment by darrenvong** [comment]
Ahh sorry I haven't been looking at this - been a bit under the weather since the last post to the point that it's even taking me out of my normal dev work for a few days, and now I'm trying my best to rest properly instead of racking my brain through coding problems (my commit graph seems to suggest otherwise so I clearly need more discipline lol 😅) 

@nabramow looks like you are giving the workaround a try and see how it goes?

**Comment by nabramow** [comment]
> Ahh sorry I haven't been looking at this - been a bit under the weather since the last post to the point that it's even taking me out of my normal dev work for a few days, and now I'm trying my best to rest properly instead of racking my brain through coding problems (my commit graph seems to suggest otherwise so I clearly need more discipline lol 😅)
> 
> @nabramow looks like you are giving the workaround a try and see how it goes?

@darrenvong Yes seems like it worked! Sorry shoulda pinged you first. My other PRs are all finally wrapped up so happy to take this back over unless you feel especially attached. I'm trying to slowly work through these package upgrades. I hope you feel better!

**Comment by nabramow** [comment]
Okay apologies but I messed this branch up real bad resolving merge conflicts with develop. Tried to fix it for ages, but decided to just copy the changes into a new branch in #5125.

**Pull request closed without merging**
