### PR TITLE
Add black and isort to CI.

### PR DESCRIPTION
**Pull request by kalvdans**
**Backend checklist**
- [ ] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [x] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by kalvdans** [comment]
Hmm, `autoflake -cr --remove-all-unused-imports src` complains on the autogenerated `src/proto/annotations_pb2_grpc.py`, how to avoid checking that file?

**Comment by kalvdans** [comment]
isort in the CI gives `fatal: not a git repository (or any of the parent directories): .git`.

That is because we run it on a subtree of the git repository *and* we specify `gitignore=true` in `pyproject.toml`.

Don't know how to proceed...

**Comment by kalvdans** [comment]
A strange thing is that I got two pipelines triggered from my first commit.

* https://gitlab.com/couchers/couchers/-/pipelines/379708704 which failed
* https://gitlab.com/couchers/couchers/-/pipelines/379709949 which succeeded

**Comment by aapeliv** [comment]
So the problem seems to be that the container doesn't contain the git repo, just the files.

A good workaround is to create a new check, say `test:backend-formatting` or something, and base it on `build:backend`.

**Comment by aapeliv** [comment]
@kalvdans happy for me to wrap this up?

**Comment by kalvdans** [comment]
> @kalvdans happy for me to wrap this up?

Yes please! I don't have much time to work on couchers :)

**Pull request merged**
