### PR TITLE
split the models in core over multiple modules

### PR DESCRIPTION
**Pull request by amdwit**
I put the messaging related classes in its own module.
Please do not comment about the code, as I still need to sanitize unneeded imports.
In this phase of this PR I am especially curious about your ideas about how to split up the classes of the model.

### CODE REVIEW

**Comment by aapeliv** [comment]
What do you think about splitting the following up further?

```
auth.py: *Token, UserSession
friendships.py: Friend*
references.py: Reference*
complaints.py: Complaint
emails.py: Email
media.py: InitiatedUpload
```

I'm not sure if this is the right naming for the files, what do you think?

**Comment by aapeliv** [comment]
Also, this probably breaks the migrations scripting. So that probably requires a bit of playing around with (to get the different `Base`s for alembic)

**Comment by kalvdans** [comment]
> Also, this probably breaks the migrations scripting. So that probably requires a bit of playing around with (to get the different `Base`s for alembic)

`Base` is a magic class with a side-effect of updating its `metadata` class variable when someone inherit from it. It is called metaprogramming, basically implementing another programming language with Python's syntax.

So everywhere where we read `Base.metadata` we have to be careful to first importing all the modules inside `couchers.models`. This is very fragile and defeats a bit the purpose of splitting up models.py. Also if someone runs `autoflake` to get rid of unused imports, it will remove those imports as well. (same problem in pytest's metaprogramming btw)

I'm a bit negaitve to such magic but once we know what is going on I don't think we need to be afraid of refactoring.

**Comment by aapeliv** [comment]
@amdwit: have you abandoned this PR? If so, I'll take it over.

**Pull request closed without merging**
