### PR TITLE
Step 1: Upgrade maplibre to version 2.4.0

### PR DESCRIPTION
**Pull request by nabramow**
Doing this one major version at a time...this time upgrading to the highest v2 version: 2.4.0. Part of #5106 .

The guide to the changes in this major version is here:
https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md#features-and-improvements-2

These are the breaking changes that affected us:

* ** Breaking Change ** removed all code related to accessToken and Mapbox specific urls starting with mapbox://. Telemetry and tracking code was removed.
* Type changes:
    - AnyLayer => LayerSpecification
    - AnySourceData => SourceSpecification
    - MapboxGeoJSONFeature => GeoJSONFeature
* It didn't mention it in the guide but the type `EventData` went away. After some sleuthing switching it out for `Event as MaplibreEvent` type seemed to do the job.
* Also not featured but had to change some `features` keys to type `Feature<Geometry, GeoJSONProperties> | undefined` from the `geojson` package. I got this from reading the Typescript errors to see what it expected.
* I had to account for some `null` and `undefined` that weren't previously being enforced by the types but now are.

**Web frontend checklist**
- [ x ] Formatted my code with `yarn format`
- [ x ] There are no warnings from `yarn lint --fix`
- [ x ] There are no console warnings when running the app
- [ x ] All tests pass
- [ x ] Clicked around my changes running locally and it works
- [ x ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by bakeiro** [comment]
@nabramow is this ready? I can perform a stress test in order to check the behavior :) [any comment/info should I know?]

**Comment by nabramow** [comment]
> @nabramow is this ready? I can perform a stress test in order to check the behavior :) [any comment/info should I know?]

Yes, it’s ready.  Everything I know I wrote in the description.

**Review by aapeliv — APPROVED** [review]
LGTM

**Comment by bakeiro** [comment]
tested & code 👍

**Review by bakeiro — APPROVED** [review]

**Pull request merged**
