### PR TITLE
Prevent zooming on mobile

### PR DESCRIPTION
**Pull request by lucaslcode**
Hopefully this prevents iOS safari zooming into text fields

### CODE REVIEW

**Comment by lucaslcode** [comment]
@aapeliv how's this

**Comment by darrenvong** [comment]
https://www.30secondsofcode.org/blog/s/zooming-accessibility-tips

Especially:
> while others such as iOS 10 ignore the suggestion entirely, so you should be aware that you might not be delivering a consistent user experience for all of your users.

I don't have an iPhone to test but not sure if this would work? And it seems anti-accessibility to disable zooming for other browsers/Android that may not be affected by this...

This might be a better solution instead? https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by lucaslcode** [comment]
It did work but you're right, it's bad accessibility. Trying this.

**Comment by darrenvong** [comment]
@aapeliv should probably check this? I don't have a physical iPhone 😅

**Review by aapeliv — APPROVED** [review]
Yep, works now!

**Pull request merged**
