### PR TITLE
minor grammatical changes for clarity

### PR DESCRIPTION
**Pull request by bhpayne**
Implements suggestions made in Couchers-org/web-frontend#116 to improve clarity of user-facing text. This change addresses part of Couchers-org/web-frontend#116.

I don't think the checklists apply since this is a change to text in a JSON file?

**Backend checklist**
- [ ] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Review by darrenvong — COMMENTED** [review]
Have you checked if these changes actually gets applied on a local build of the app?

This would be the correct place to fix it if we had fully internationalised our app to read **everything** from the JSON, but since you caught us in the middle of the transition... you may have to change the actual constants used in the relevant parts of the code for it to show up **now**

**Comment by bhpayne** [comment]
@darrenvong thanks for explaining. No, I haven't checked. I will try getting a local build (I haven't done that before).

**Comment by darrenvong** [comment]
There's a [web specific README](https://github.com/Couchers-org/couchers/tree/develop/app/web#setting-up-the-dev-environment) for setting up locally for frontend contribution only, but if anything is unclear, feel free to ask :)

**Comment by aapeliv** [comment]
How'd you go @bhpayne?

**Pull request closed without merging**
