### PR TITLE
[MRG] Backend-tests: Wait for all grpc server threads to stop.

### PR DESCRIPTION
**Pull request by kalvdans**
The stop method of grpc.Server doesn't block but instead returns a `threading.Event` that could be used to do a blocking wait.

Fixes the following intermittent error:
```
47___________________ ERROR at teardown of test_invalid_token ____________________
48    @pytest.fixture()
49    def check_fd_leak():
50        import psutil
51
52        thisproc = psutil.Process()
53
54        open_files_before_test = thisproc.num_fds()
55
56        yield
57
58        open_files_after_test = thisproc.num_fds()
59>       assert open_files_before_test == open_files_after_test
60E       assert 13 == 15
61src/tests/test_fixtures.py:289: AssertionError
```

Only reproducable when starting postgres without the flags `-F --synchronous_commit=off --full_page_writes=off`.

> Threads, why does it have to be threads?
 -- Indiana Jones

### CODE REVIEW

**Comment by aapeliv** [comment]
Nice! There's two other instances of this in the code base as well, do you mind adding a `.wait()` for those too?

**Comment by kalvdans** [comment]
> Nice! There's two other instances of this in the code base as well, do you mind adding a `.wait()` for those too?

Good catch! Consider it done!

**Comment by kalvdans** [comment]
Hmm, gitlab CI still not happy :/ https://gitlab.com/couchers/couchers/-/jobs/852888415
Back to the drawing table.

**Comment by kalvdans** [comment]
Looking at the source code to `grpc`, it makes no intention to join its threads, and I'm not even sure if you can join a thread in a Future. I think we have to back out the fd leak test.

**Comment by aapeliv** [comment]
OK, should I revert that commit?

**Comment by kalvdans** [comment]
Yes please, or I will do it in 10 hours when home

**Comment by kalvdans** [comment]
I've redone this PR now with bits and pieces from previous failed attempts. No leakage tests are done but we still try to close threadpools in a good manner. New review please!

**Comment by aapeliv** [comment]
Nice! CI passes: https://gitlab.com/couchers/couchers/-/pipelines/218177969

**Review by aapeliv — APPROVED** [review]
LGTM.

**Comment by aapeliv** [comment]
I've merged this, I don't know why Github isn't happy and doesn't notice

**Comment by kalvdans** [comment]
> I've merged this, I don't know why Github isn't happy and doesn't notice

Github couldn't automerge for some reason. I merged manually and pushed to this branch, then suddenly it understood it had been merged.

**Comment by aapeliv** [comment]
Might've been due to the big react merge in between

**Pull request closed without merging**
