### PR TITLE
Tweak cookie settings

### PR DESCRIPTION
**Pull request by aapeliv**
As discussed in meeting

### CODE REVIEW

**Comment by lucaslcode** [comment]
I get ```Access to XMLHttpRequest at 'http://localhost:8888/org.couchers.auth.Auth/Login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

**Comment by aapeliv** [comment]
Yeah, I'm working on it... Envoy is returning a 503 because I've misconfigured the origin matching.

**Comment by aapeliv** [comment]
@lucaslcode: Does it work for you now?

**Comment by lucaslcode** [comment]
No, set-cookie is blocked because SameSite=None requires Secure=True

**Comment by lucaslcode** [comment]
Blocked, "had the secure attribute but not sent over a secure connection"

**Review by lucaslcode — APPROVED** [review]
Working locally. Check production before merge

**Pull request merged**
