### PR TITLE
change ids to 64 bit signed in proto and model

### PR DESCRIPTION
**Pull request by amdwit**
I changed the ids to BigInteger in models.py and to int64 in the proto files
The migration files are coming soon in this PR.

### CODE REVIEW

**Review by kalvdans — APPROVED** [review]
Good to use BigInteger in the backend to avoid hitting the 2 giga limit. At work we just hit the limit due to a bug where we constantly deleted and created rows ;)

I don't know why we need to change the API though. I think we can aim to keep identifiers positive below 2^52 and then it doesn't matter if we declare them as uint64 or int64 in the API.

But I'm fine with int64 too so giving a :+1:

**Comment by aapeliv** [comment]
Looks OK for now. I hope the migrations aren't too hairy!

**Comment by amdwit** [comment]
Yes, the migrations ... 
I will restart the docker container to test.

**Comment by aapeliv** [comment]
>  The migration files are coming soon in this PR.

The migrations should have been part of this PR, not in a separate PR. They're part of the same change set. The changes in the database and the created schemas need to be applied "atomically" to `develop`. Right now develop has a mismatch between `models.py` and the actual database that will be running in postgres.

**Pull request merged**
