### PR TITLE
Frontend/design/signup background

### PR DESCRIPTION
**Pull request by alexishonzik**
This PR is to resolve Issue #983. I removed the div that placed the background image for the form on the mobile view, so that the background is now white. This resolves the problem with not being able to clearly read the form.

### CODE REVIEW

**Review by lucaslcode — CHANGES_REQUESTED** [review]
Thanks! Can you also remove the one in `login.tsx` and then remove the `backgroundBlurImage` style, since it will no longer be used?

**Comment by alexishonzik** [comment]
Just changed `login.tsx` and removed `backgroundBlurImage`!

**Review by lucaslcode — APPROVED** [review]
Thanks for your contribution!

**Comment by lucaslcode** [comment]
closes #983

**Pull request merged**
