### PR TITLE
Docs: Handbook adjusted and line-shifted

### PR DESCRIPTION
**Pull request by comradekingu**
**Backend checklist**
- [ ] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [ ] Formatted my code with `yarn format && yarn lint --fix`
- [ ] There are no warnings from `yarn lint`
- [ ] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [ ] All tests pass
- [ ] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by aapeliv** [comment]
What's the purpose of the line breaks?

**Comment by comradekingu** [comment]
@aapeliv Makes it easier to read, and appear as something that shouldn't just be skipped over.

**Comment by jesseallhands** [comment]
Thanks @comradekingu for taking the time to go through this! I had a look and the line breaks shouldn't be necessary anymore. We made some changes to the CSS to fix the navigation issue and spacing looks good now too here:  https://couchers.org/handbook/ 

It's great that you're helping out with the project! It would be great if you could have a look at some of the other issues and see if you could tackle some more. Is it okay if I also reach out for your help with the handbook when we make some updates in the future?

**Comment by comradekingu** [comment]
@AllhandsNoFeet
Sure. Hoping we see eye to eye on the changes alluding to not banning resulting outcomes, even if the platform doesn't operate to facilitate them. Also hoping to see a AGPLv3+ license instead of MIT.
I'll care about that sort of thing and fix issues as I go :)

**Pull request closed without merging**
