### PR TITLE
Backend/refactoring/small changes inspired by delete account

### PR DESCRIPTION
**Pull request by ShmuelTreiger**
Various minor additions/changes. Biggest is a password_reset_token purge

**Backend checklist**
- [x] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [x] All tests pass
- [ ] Run the backend locally and it works
- [ ] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

### CODE REVIEW

**Comment by kalvdans** [comment]
I'm unsure what the workflow is with PR into a feature branch. Please do preparation cleanups as a PR against `develop`.

**Comment by ShmuelTreiger** [comment]
@kalvdans I did it against PR b/c I change `make_invisible`--which is used in PR--to `delete_user`. Plan would be to merge this once base PR has been merged.

Sorry, should have made a note.

**Comment by kalvdans** [comment]
Please mark it as draft until it can be merged.

**Comment by aapeliv** [comment]
We should just merge all the token deletion bg jobs into one. No need to run them separately.

**Comment by ShmuelTreiger** [comment]
@aapeliv I was wondering that. I was also wondering about making a parent class and inheritance class for tokens. Thoughts on that? Might be worth doing both at once if we do.

**Pull request merged**
