### PR TITLE
[MRG] Reject uppercase usernames

### PR DESCRIPTION
**Pull request by kalvdans**
Follow-up to https://github.com/Couchers-org/couchers/issues/204 , where it was discussed to reject uppercase usernames in the backend. This PR implements that.

### CODE REVIEW

**Review by lucaslcode — DISMISSED** [review]

**Comment by aapeliv** [comment]
The build is now broken, since `username` is not defined.

If you think we should go back to not lower()-ing the username on the backend, please revert 5e1afac9c99e2f406a9816dba0834394fca199ec where I added these.

I think it'd be nicer to just lower() on the backend, but add a note on the frontend that usernames are lowercase. For instance, on some phones, fields are automatically sentence cased. Sure, this should be fixed on the frontend, but I still feel it's less friction to just do the lowercasing of usernames on the backend?

**Review by aapeliv — CHANGES_REQUESTED** [review]
See comment

**Comment by kalvdans** [comment]
Sloppy by me to not re-run the tests :/

In HTML, there seems to be an `<input autocapitalize=off>` parameter. I've fixed the build but I'll leave the PR open for more collection of pros/cons.

**Comment by aapeliv** [comment]
Does this still have the `field = field.lower()` in `app/backend/src/couchers/db.py`?

**Comment by kalvdans** [comment]
> Does this still have the `field = field.lower()` in `app/backend/src/couchers/db.py`?

Yes. For emails... but it might not work if we don't lower them before storing in the database.

**Comment by aapeliv** [comment]
You should remove that as well, I think

**Review by aapeliv — APPROVED** [review]

**Pull request merged**
