### PR TITLE
Frontend/refactor/fix maplibre dependencies

### PR DESCRIPTION
**Pull request by vrouilhac**
I tried to fix the issue and I replaced the import. I also updated the dependencies. And the import error disappeared.

### CODE REVIEW

**Comment by vrouilhac** [comment]
I solved the merging conflict and checked for changes.

The only changes in package.json is :

maplibre version ^1.13.0-rc.4 ->  ^1.13.0-rc.5

**Review by lucaslcode — CHANGES_REQUESTED** [review]
Looks good, but all the indentation in `package.json` is changed, please put it back :D

**Comment by vrouilhac** [comment]
I faced some issues with pull but in the last commit I solved those and pushed a clean version. package.json is now updated with latest version of maplibre. :+1: and spaced is back to normal.

**Review by lucaslcode — APPROVED** [review]
Thanks! By the way I emailed your from your web-site

**Comment by vrouilhac** [comment]
> Thanks! By the way I emailed your from your web-site

It seems I did not receive it. After sending the mail did you see the notification saying I'm replying soon ?

**Pull request merged**
