### PR TITLE
Check username isn't already in use when completing sign up

### PR DESCRIPTION
**Pull request by satvik6005**
**Backend checklist**
- [x] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [ ] All tests pass
- [ ] Run the backend locally and it works

made some changes to username_available function in auth.py updated it to check also the signup flow table if 2 simultaneous requestt are working

### CODE REVIEW

**Comment by satvik6005** [comment]
@aapeliv  can u tell me please tell me how to run tests on my code

**Comment by aapeliv** [comment]
Please follow instructions here: https://github.com/Couchers-org/couchers/tree/develop/app/backend#running-tests-locally

**Comment by satvik6005** [comment]
> Please follow instructions here: https://github.com/Couchers-org/couchers/tree/develop/app/backend#running-tests-locally

i need a favor I am getting a lot of trouble on my machine regarding  less memory and all can u please run the test on my merge request
thank you

**Comment by satvik6005** [comment]
> > Please follow instructions here: https://github.com/Couchers-org/couchers/tree/develop/app/backend#running-tests-locally
> 
> i need a favor I am getting a lot of trouble on my machine regarding less memory and all can u please run the test on my merge request
> thank you

Hello @aapeliv please reply to my mentioned issue ☝☝

**Comment by aapeliv** [comment]
No, I can't run the tests for you. You have to figure out how to run them locally yourself.

**Comment by satvik6005** [comment]
@aapeliv during signup username availability is being checked from the user table but not from the signupflow table both the tables must be checked because to user with same name could be signing up simultaneously.

**Comment by aapeliv** [comment]
@stifler6005: I'm sorry, but I don't think we can merge this PR.

* We are having a lot of trouble trying to work this out together: you're writing a lot of unrelated messages and tagging me in them. You seem to expect me to hold your hand through this process and do a lot of things for you which you need to figure out yourself. We're not making any progress here.
* You keep on pinging me without having made any progress or having responded to what I wrote
* The code is broken and clearly does not do what it should
* The commit history is a mess
* You have not run the tests
* This is the second time this happens after your first botched PR, and the situation is not getting better

Given these points, I think it's better you find another codebase to help out on. All the best!

**Comment by satvik6005** [comment]
@apeliv i apologise for the inconvenience i will try to be more careful in
future.

**Pull request closed without merging**
