### PR TITLE
Add cache headers back in after flask 2

### PR DESCRIPTION
**Pull request by aapeliv**
Fixes #1234

### CODE REVIEW

**Comment by kalvdans** [comment]
It would be cleaner if we merge https://github.com/Couchers-org/couchers/pull/1236 first and then we can explicitly bump Flask version in this PR.

**Comment by aapeliv** [comment]
So what should I change the requirements line to here?

**Comment by kalvdans** [comment]
Flask>=2,<3 seems to work :heart:

**Comment by kalvdans** [comment]
nodejs have notations like ^2.0.0 but it seems pip doesn't.

**Review by kalvdans — APPROVED** [review]
If CI is happy, I am!

**Comment by aapeliv** [comment]
CI sometimes spawns two pipelines, I killed the one with non-media jobs, but the media stuff went through

https://gitlab.com/couchers/couchers/-/pipelines/302012371

**Pull request merged**
