### PR TITLE
Allow messaging anybody

### PR DESCRIPTION
**Pull request by aapeliv**
* Backend: removes the requirement to be friends to message a user
* Frontend: add button to message a user regardless of friendship status
* Frontend: add a button next to messages to report that message

Screenshot from 2021-10-14 12-58-20

Closes part of #2083

**Backend checklist**
- [x] Formatted my code by running `autoflake -r -i --remove-all-unused-imports src && isort . && black .` in `app/backend`
- [ ] Added tests for any new code or added a regression test if fixing a bug
- [x] All tests pass
- [ ] Run the backend locally and it works
- [x] Added migrations if there are any database changes, rebased onto `develop` if necessary for linear migration history

**Web frontend checklist**
- [x] Formatted my code with `yarn format && yarn lint --fix`
- [x] There are no warnings from `yarn lint`
- [x] There are no console warnings when running the app
- [ ] Added any new components to storybook
- [ ] Added tests where relevant
- [x] All tests pass
- [x] Clicked around my changes running locally and it works
- [ ] Checked Desktop, Mobile and Tablet screen sizes

### CODE REVIEW

**Comment by aapeliv** [comment]
Frontend: It would be great to get the chat id into the message so that it can be added to the `contentRef` for the flag button, but that requires passing it down a few levels into subcomponents, so not sure how to do that exactly

**Comment by darrenvong** [comment]
Isn't the `messageId` globally unique at the moment since all messages are on the same table? Would that not be sufficient for the `contentRef`?

**Comment by aapeliv** [comment]
Yes, it suffices for the time being; but it’d be easier for the support team to have both. So not a blocker.

**Comment by darrenvong** [comment]
Should this be added to the `content_ref` docs as well?

**Review by darrenvong — DISMISSED** [review]
Web frontend looks fine to me!

**Comment by aapeliv** [comment]
> Should this be added to the `content_ref` docs as well?

Yes, thanks

**Review by kalvdans — APPROVED** [review]
Backend looks fine!

Missing a link to some motivation for the decision though.

**Comment by aapeliv** [comment]
> Missing a link to some motivation for the decision though.

It's been discussed a lot on Slack

**Pull request merged**
