### PR TITLE
inputRef changed with focus added on password

### PR DESCRIPTION
**Pull request by vrouilhac**
I created an account and set a password to check if it works. And after reading the react-hook-form "register" is working and if we click on continue without giving password the { require: true } is working.

The password input is focused and the behaviour is the validation behaviour is the same as before.

### CODE REVIEW

**Comment by vrouilhac** [comment]
I just ran yarn format and face an issue. It seems that git diff print changes on files I didn't touch, should I push it anyway ?

**Comment by lucaslcode** [comment]
> should I push it anyway

Yes, just do a separate commit.

**Comment by vrouilhac** [comment]
> > should I push it anyway
> 
> Yes, just do a separate commit.

Done

**Review by lucaslcode — DISMISSED** [review]
Lgtm! You should clone the repo instead of using your fork next time, that way the CI will run the checks.

**Comment by vrouilhac** [comment]
> Lgtm! You should clone the repo instead of using your fork next time, that way the CI will run the checks.

Sorry i didn’t know that, i’ll do it next time 🙏

**Comment by lucaslcode** [comment]
You'll need to resolve the merge conflicts to merge, I think it's just formatting

**Comment by vrouilhac** [comment]
> You'll need to resolve the merge conflicts to merge, I think it's just formatting

Yes maybe, but I'm kinda stuck here, I don't see where the formating is blocking on this file and git tells me that's the working tree is clean, nothing to commit. :/

**Comment by Vincent-Projects** [comment]
> You'll need to resolve the merge conflicts to merge, I think it's just formatting

Yes maybe, but I'm kinda stuck here, I don't see where the formating is blocking on this file and git tells me that's the working tree is clean, nothing to commit. :/

**Comment by lucaslcode** [comment]
> nothing to commit

Make sure you have the latest develop, and you are on your branch, then do `git merge develop`

**Comment by vrouilhac** [comment]
> > nothing to commit
> 
> Make sure you have the latest develop, and you are on your branch, then do `git merge develop`

Now I push the changes ?

**Comment by vrouilhac** [comment]
Seems like it worked thanks for your help @lucaslcode :pray:

**Review by lucaslcode — APPROVED** [review]

**Pull request merged**
